#!/bin/bash
if [ -f /etc/sysconfig/livesd ]; then
        . /etc/sysconfig/livesd
fi
RETVAL=0
prog="lives"
LIVES=/usr/local/reach/lives
LIVED=/usr/local/reach/lived
 
case "$1" in
        start)
        	echo -n $"Starting $prog:"
        	$LIVED&
       		RETVAL=$?
        	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/livesd
        	echo
                ;;
        stop)
		echo -n $"Stopping $prog:"
	        killall -9 lived
		killall -9 lives
	        RETVAL=$?
        	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/livesd
        	echo
                ;;
        restart)
                $0 stop
                $0 start
                ;;
        reload)
		echo -n $"Reloading $prog:"
        	killproc $LIVES -HUP
        	RETVAL=$?
        	echo
                ;;
        status)
                status $LIVED
                RETVAL=$?
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac
exit $RETVAL
